### ISSUE TITLE
A Fully FTCLib Quickstart

### ISSUE THREAD

**Issue by litehed** [FTCLib/RoadRunner-FTCLib-Quickstart#9]
I feel like many of the files are created not properly utilizing FTCLib. I think it would be better to write classes like the SampleDrives using that library. It would help blend the code easier, make it easier to read and use these classes, and it would fit much better with the theme of the quickstart and FTCLib as a whole.

**Comment by JIceberg** [comment]
This will be done in a separate repository. Stay tuned.
